<html itemscope itemtype="http://schema.org/Product" prefix="og: http://ogp.me/ns#" xmlns="http://www.w3.org/1999/html">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="content-type" content="text/html;charset=utf-8">
        <link rel="stylesheet" href="https://s3-ap-southeast-1.amazonaws.com/qiscus-sdk/web/latest/qiscus-sdk.css">
        <link rel="stylesheet" href="https://s3-ap-southeast-1.amazonaws.com/qiscus-sdk/we/latest/qiscus-sdk.css">
        <style type="text/css">
            #meet {
                position: absolute;
                bottom: 0;
                right: 0;
                width: 100%;
                height: 100%;
                overflow: hidden;
            }
        </style>
    </head>
    <body>
        <div id="meet"></div>
        <script src="https://dgcall.qiscus.com/qiscus/external_api.js"></script>
        <script>
            var room = window.location.pathname.split('/')[2];
            var domain = "dgcall.qiscus.com";
            var options = {
                roomName: room,
                parentNode: document.querySelector('#meet'),
                configOverwrite: {},
                interfaceConfigOverwrite: {
                    TOOLBAR_BUTTONS: [
                        'microphone', 'camera', 'hangup'
                    ],
                    VIDEO_LAYOUT_FIT: 'both',
                    DEFAULT_REMOTE_DISPLAY_NAME: 'Guest',
                    APP_NAME: 'Qiscus',
                    NATIVE_APP_NAME: 'Qiscus',
                    PROVIDER_NAME: 'Qiscus',
                }
            }
            var api = new QiscusMeetExternalAPI(domain, options);

            api.executeCommand('displayName', 'Users');

            api.on('readyToClose', () => {
                // alert("panggil ready to close")
                console.log("ini panggil readyToClose")
                //tricky to close windows
                var rejected = {
                    "sender": room,
                    "event": "rejected",
                    "active": "false"
                }
                qiscus.publishEvent(room, rejected)
                qiscus.unsubscribeEvent(room)
    
                // var win = window.open("about:blank", "_self");
                // win.close();
            });

            api.on('participantJoined', (data) => {
                //tricky to close windows
               // alert("Get Name : "+ data.displayName );
            });

            api.on('videoConferenceLeft', (data) => {
                setTimeout(function(){ 
                            var win = window.open("about:blank", "_self");
                            win.close();
                    }, 2000);
            });

            api.on('participantLeft', (data) => {
                if(api.getNumberOfParticipants() === 1){
                    setTimeout(function(){ 
                        if(api.getNumberOfParticipants() === 1) {
                            var win = window.open("about:blank", "_self");
                            win.close();
                        }
                    }, 10000);
                }
            });
        </script>
        <!-- <script src="https://unpkg.com/qiscus-sdk-core"></script> -->
        <script src="https://unpkg.com/lodash@4.17.4/lodash.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/emojione/2.2.7/lib/js/emojione.min.js"></script>
        <script src="https://s3-ap-southeast-1.amazonaws.com/qiscus-sdk/web/latest/qiscus-sdk.js"></script>
        <script>
             QiscusSDK.core.init({
                AppId: "sdksample",
                options: {
                loginSuccessCallback: function (data) {
                    console.log('loginSuccessCallback', data);
                    var userData = {
                    userId: "user3_sample_call@example.com",
                    secret: "123",
                    username: "User 3 Sample Call",
                    avatarURL: ""
                    };
                }
                }
            });
            QiscusSDK.core.setUser(
                /* userId */ "user3_sample_call@example.com",
                /* password */ "123",
                /* displayName */ "User 3 Sample Call",
                /* avatarURL */ ""
            );
        </script>
    </body>
</html>
