<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <script src="../assets/js/libs/jquery-2.1.1.min.js"></script>
    <script src="../assets/js/libs/strophe/strophe.js"></script>
    <script src="../assets/js/libs/strophe/strophe.disco.min.js?v=1"></script>
    <script src="https://qiscus-call-sdk.s3-ap-southeast-1.amazonaws.com/meet/lib-qiscus-meet.min.js"></script>
    <script src="../assets/js/example.js" ></script>
    <link rel="stylesheet" href="../assets/css/all.css">
</head>
<body>
    <!-- <a href="#" onclick="unload()">Unload</a> -->
    <!-- <a href="#" onclick="mutedVideo()">On/Off Camera</a>
    <a href="#" onclick="mutedAudio()">On/Off Audion</a>
    <a href="#" onclick="hangup()">hangup</a> -->
    <div id="audioOutputSelectWrapper" style="display: none;">
        Change audio output device
        <select id="audioOutputSelect" onchange="changeAudioOutput(this)"></select>
    </div>
    <div class="vertical-filmstrip filmstrip">
        <div class="filmstrip__videos" id="remoteVideos">
                <div class="filmstrip__videos" id="filmstripLocalVideo" style="width: 124px;">
                        <div id="remote-video" class="small-video"></div>
                </div>
        </div>
    </div>
    
    
    <!-- <video id="localVideo" autoplay="true"></video> -->
    <!-- <audio id="localAudio" autoplay="true" muted="true"></audio> -->
    <div class="new-toolbox visible" id="new-toolbox ">
        <div class="toolbox-background"></div>
        <div class="toolbox-content">
            
        <div class="button-group-center">
            <div aria-label="Toggle mute audio" class="toolbox-button">
                <button id="btn-audio" onclick="mutedAudio()" >Audio</button>
            </div>
            <div aria-label="Leave the call" class="toolbox-button">
                <button id="btn-end-call" onclick="hangup()">EndCall</button>
            </div>
            <div aria-label="Toggle mute video" class="toolbox-button">
                <button id="btn-video" onclick="mutedVideo()" >Video</button>
            </div>
        </div>
    </div>

    </div>
</div>
<div id="largeVideoWrapper"><video autoplay='1' id='localVideo' class='largeVideo'/></div>
<div id="largeVideoWrapper"><audio autoplay='1' muted='true' id='localAudio' class='largeVideo' /></div>
</body>
</html>
