<html itemscope itemtype="http://schema.org/Product" prefix="og: http://ogp.me/ns#" xmlns="http://www.w3.org/1999/html">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="content-type" content="text/html;charset=utf-8">
        <style type="text/css">
            #meet {
                position: absolute;
                bottom: 0;
                right: 0;
                width: 100%;
                height: 100%;
                overflow: hidden;
            }
        </style>
    </head>
    <body>
        <div id="meet"></div>
        <script src="https://meet.qiscus.com/qiscus/external_api.js"></script>
        <script>
            var room = window.location.pathname.split('/')[2];
            var domain = "meet.qiscus.com";
            var options = {
                roomName: room,
                parentNode: document.querySelector('#meet'),
                configOverwrite: {},
                interfaceConfigOverwrite: {
                    TOOLBAR_BUTTONS: [
                        'microphone', 'camera', 'hangup'
                    ],
                    VIDEO_LAYOUT_FIT: 'both',
                    DEFAULT_REMOTE_DISPLAY_NAME: 'Guest',
                    APP_NAME: 'Qiscus',
                    NATIVE_APP_NAME: 'Qiscus',
                    PROVIDER_NAME: 'Qiscus',
                }
            }
            var api = new QiscusMeetExternalAPI(domain, options);

            api.executeCommand('displayName', 'D Family');

            api.on('readyToClose', () => {
                //tricky to close windows
                var win = window.open("about:blank", "_self");
                win.close();
            });
        </script>
    </body>
</html>